<a href="https://colab.research.google.com/github/xg6144/Machine_Practice/blob/main/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#랜덤포레스트
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

wine = pd.read_csv('https://bit.ly/wine-date')

wine_data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(
    wine_data, target, random_state = 42
)

from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs=-1, random_state = 42)

scores = cross_validate(rf, train_input, train_target,
                        return_train_score = True, n_jobs=-1) #교차검증

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.997844759088341 0.8914208392565683


In [ ]:
rf.fit(train_input, train_target)

print(rf.feature_importances_) #중요도

[0.23155241 0.49706658 0.27138101]


In [ ]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42) #RandomForestClassfier는 자체적으로 모델을 평가한다. oob_score 하이퍼파라미터를 True로 설정하면 oob_score 점수를 얻을 수 있다.
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8981937602627258


In [ ]:
#EXTRA TREE
#Extra Tree는 RandomForest와 비슷한 방식으로 작동한다.
#Extra Tree는 BootStrap Sample을 사용하지 않는다. - Node를 분할할 때 가장 좋은 것을 찾는 게 아닌 Random하게 분할한다.
#과대 적합을 막고 검증 세트의 점수를 높인다. 회귀는 ExtraTressRegressor
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.997844759088341 0.8903937240035804


In [ ]:
et.fit(train_input, train_target)
print(et.feature_importances_) #alcohol, sugar, pH 

[0.20702369 0.51313261 0.2798437 ]


In [ ]:
#Gradient Boosting 
#Depth가 얕은 경우 Gradient Boosting으로 하면 과대적합을 방지할 수 있다. 경사하강법을 사용해 트리를 생성
#Tree를 늘려도 과대적합을 막는데 효율적이다.
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(random_state=42)
scores = cross_validate(
    gbc, train_input, train_target,
    return_train_score = True, n_jobs=-1
)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8894704231708938 0.8715107671247301


In [ ]:
gbc.fit(train_input, train_target)
print(gbc.feature_importances_)

[0.12517641 0.73300095 0.14182264]


In [ ]:
#Histogram Based Gradient Boosting
#정형데이터를 다루는 알고리즘 중 가장 많이 사용된다.
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state = 42)
scores = cross_validate(
    hgb, train_input, train_target,
    return_train_score = True, n_jobs = -1
)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9380129799494501 0.8805410414363187


In [ ]:
hgb.fit(train_input, train_target)
print(rf.feature_importances_)
print(hgb.score(test_input, test_target))

[0.23155241 0.49706658 0.27138101]
0.8584615384615385


In [ ]:
from sklearn.ensemble import HistGradientBoostingRegressor

hgbr = HistGradientBoostingRegressor()
scores = cross_validate(
    hgbr, train_input, train_target,
    return_train_score = True, n_jobs = -1
)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

hgbr.fit(train_input, train_target)
print(hgbr.predict([[9, 2, 3.5]])) #와인예측모델

0.7024475200988506 0.5215015314918651
[0.09152929]
